# Site configuration for GitHub Pages
name: Louis Hyman
url: ""
baseurl: ""
title: "Louis Hyman"
description: "Historian of work, business, and capitalism"
email: lhyman@gmail.com
permalink: pretty
markdown: kramdown
theme: jekyll-theme-slate
collections: []
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
