# Site configuration for GitHub Pages
name: Louis Hyman
url: ""
baseurl: ""
title: "Louis Hyman"
description: "Historian of work, business, and capitalism"
email: lhyman@gmail.com
permalink: pretty
markdown: kramdown
theme: slate
collections: []
